#! /bin/bash


# VARIABLES ###################################################################
_USER=${SUDO_USER}
_HOME=$(eval echo ~${_USER})
_KEYDIR="${_HOME}/.scrypt"
_PROFILES="${_KEYDIR}/.kpxc.profiles"

# Set path variables
_CURRDIR="$(pwd)"
_SOURCE="${BASH_SOURCE[0]}"
while [ -h "$_SOURCE" ]; do
  _BASEDIR="$( cd -P "$( dirname "$_SOURCE" )" >/dev/null 2>&1 && pwd )"
  _SOURCE="$(readlink "$_SOURCE")"
  [[ $_SOURCE != /* ]] && _SOURCE="$_BASEDIR/$_SOURCE"
done
_BASEDIR="$( cd -P "$( dirname "$_SOURCE" )" >/dev/null 2>&1 && pwd )"


# FUNCTION DEFINITION #########################################################
# Displays help message
display_help(){
    local MESSAGE=$1
    [ ! -z "${MESSAGE}" ] && echo "${MESSAGE}"
    cat <<EOF

    Usage:  $0 <profile> COMMAND OPTIONS...

            For command and option reference,
            see keepassxc-cli docs.
EOF
}

# Displays error message
display_error(){
    cat <<< "ERROR: $@" 1>&2;
}

# Load profile
profile_load(){
    local NAME=$1
    _KEYNAME=$(cat "${_PROFILES}" | grep "^${NAME}\s" | awk '{print $2}')
    _DATABASE=$(cat "${_PROFILES}" | grep "^${NAME}\s" | awk '{print $3}')
}
# Save profile
profile_save(){
    local PROFILE_NAME=$1
    local PROFILE_KEY=$2
    local KEEPASS_DB=$3

    sed -i "/^${PROFILE_NAME}\s/d" "${_PROFILES}"
    echo "${PROFILE_NAME}    ${PROFILE_KEY}    ${KEEPASS_DB}" >> "${_PROFILES}"
    echo "${PROFILE_NAME}    ${PROFILE_KEY}    ${KEEPASS_DB}"
}


# PARSE CLI ARGUMENTS #########################################################
_NAME=$1
_COMMAND=$2

# Name parameter
[ -z "${_NAME}" ] && {
    display_help "Obligatory profile 'name' parameter is missing."
    exit 1
}

# PREPARE #####################################################################
## assert and load profile
touch "${_PROFILES}"
profile_load "${_NAME}"

## ask for missing information
[ -z "${_KEYNAME}" ] && {
    read -p "KEYNAME: " _KEYNAME
    _CHANGED=True
}
[ -z "${_DATABASE}" ] && {
    read -p "DATABASE: " _DATABASE
    _CHANGED=True
}
## save new information
[ -z "${_CHANGED}" ] || {
    profile_save "${_NAME}" "${_KEYNAME}" "${_DATABASE}"
}


# MAIN ########################################################################
"${_BASEDIR}"/sscrypt "${_KEYNAME}" lookup Title "${_NAME}" | keepassxc-cli ${_COMMAND} --quiet "${_DATABASE}" "${@:3}"
#keepassxc-cli ${_COMMAND} --quiet "${_DATABASE}" "${@:3}" <<< "${_BASEDIR}"/sscrypt "${_KEYNAME}" lookup Title "${_NAME}"
#echo keepassxc-cli ${_COMMAND} --quiet "${_DATABASE}" "${@:3}"
